name: Setup Rust Builder
description: 'Prepare Rust Build Environment'
inputs:
  cache-key:
    description: 'the rust cache key suffix'
    required: false
    default: ''
  target:
    description: 'the rust target to build'
    required: false
    default: x86_64-unknown-linux-gnu

runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@stable
      id: toolchain
      with:
        toolchain: stable
        targets: ${{ inputs.target }}

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/
          ~/.cargo/bin/cargo-*
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ steps.toolchain.outputs.cachekey }}-${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ steps.toolchain.outputs.cachekey }}
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          ${{ runner.os }}-cargo

    - name: Setup rust related environment variables
      shell: bash
      run: |

        # Enable terminal color
        echo "CARGO_TERM_COLOR=always" >> $GITHUB_ENV
        # Disable full debug symbol generation to speed up CI build and keep memory down
        # "1" means line tables only, which is useful for panic tracebacks.
        echo "RUSTFLAGS=-C debuginfo=1" >> $GITHUB_ENV
        # Enable backtraces
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        # Enable logging
        echo "RUST_LOG=info" >> $GITHUB_ENV
        # Enable sparse index
        echo "CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse" >> $GITHUB_ENV
        # Enable sccache
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
