[workspace]
default-members = ["core", "sql", "driver", "macros", "cli"]
members = [
    "core",
    "sql",
    "driver",
    "macros",
    "cli",
    "bindings/python",
    "bindings/nodejs",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.19.4"
license = "Apache-2.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
categories = ["database"]
keywords = ["databend", "database"]
repository = "https://github.com/datafuselabs/bendsql"

[workspace.dependencies]
databend-client = { path = "core", version = "0.19.4" }
databend-driver = { path = "driver", version = "0.19.4" }
databend-driver-core = { path = "sql", version = "0.19.4" }
databend-driver-macros = { path = "macros", version = "0.19.4" }

[patch.crates-io]
pyo3-asyncio = { git = "https://github.com/everpcpc/pyo3-asyncio", rev = "42af887" }
