[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
unlicensed = "warn"
allow = [
    "MIT",
    "CC0-1.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "ISC",
    "MPL-2.0",
    "BSL-1.0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
]

[bans]
multiple-versions = "allow"
wildcards = "warn"
highlight = "all"

[sources]
unknown-git = "deny"
