name: 'Check'
description: 'Check will do all essential checks'
inputs:
  github_token:
    description: "Github Token"
    required: true
runs:
  using: "composite"
  steps:

    - name: Check Apache License Header
      uses: korandoru/hawkeye@v3

    - name: Typos
      uses: crate-ci/typos@master

    - name: Format
      shell: bash
      run: |
        cargo fmt --all -- --check

    - name: Audit dependencies
      shell: bash
      run: |
        cargo audit

    - name: Machete
      shell: bash
      run: |
        cargo machete

    - name: Clippy
      shell: bash
      run: |
        cargo clippy --all-targets -- -D warnings
