[package]
name = "bendsql"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "Databend Native Command Line Tool"
categories = ["database"]
keywords = ["databend", "database", "cli"]
repository = "https://github.com/datafuselabs/databend-client"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
atty = "0.2.14"
clap = { version = "4.1.0", features = ["derive", "env"] }
comfy-table = "6.1.4"
databend-driver = { path = "../driver", version = "0.2.5", features = ["rustls", "flight-sql"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
humantime-serde = "1.1.1"
url = { version = "2.3.1", default-features = false }
indicatif = "0.17.3"
itertools = "0.10.5"
logos = "0.13.0"
rustyline = "11.0.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
shlex = "1.1.0"
sqlformat = "0.2.1"
strum = "0.24"
strum_macros = "0.24"
tokio = { version = "1.26", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "parking_lot",
] }
toml = "0.7.3"

[[bin]]
name = "bendsql"
path = "src/main.rs"
doctest = false
test = false
