[package]
name = "bendsql"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Databend Native Cli tool"
categories = ["database"]
keywords = ["databend", "database", "cli"]
repository = "https://github.com/datafuselabs/databend-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = { version = "36.0.0" }
arrow-cast = { version = "36.0.0", features = [
    "prettyprint",
] }
arrow-flight = { version = "36.0.0", features = [
    "flight-sql-experimental",
] }

atty = "0.2.14"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
rustyline = "11.0.0"
shlex = "1.1.0"
tokio = { version = "1.26", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "parking_lot",
] }

async-trait = "0.1.68"
clap = { version = "4.1.0", features = ["derive"] }
comfy-table = "6.1.4"
indicatif = "0.17.3"
logos = "0.12.1"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
strum = "0.24"
strum_macros = "0.24"
tonic = { version = "0.8", default-features = false, features = [
    "transport",
    "codegen",
    "tls",
    "prost",
] }
toml = "0.7.3"
humantime-serde = "1.1.1"
itertools = "0.10.5"
sqlformat = "0.2.1"

[[bin]]
name = "bendsql"
path = "src/main.rs"
doctest = false
test = false
