[package]
name = "bendsql"
description = "Databend Native Command Line Tool"
categories = ["database"]
keywords = ["databend", "database", "cli"]

version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
databend-driver = { workspace = true, features = ["rustls", "flight-sql"] }

anyhow = "1.0.70"
async-trait = "0.1.68"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
clap = { version = "4.1.0", features = ["derive", "env"] }
comfy-table = "6.1.4"
csv = "1.2.1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
humantime-serde = "1.1.1"
indicatif = "0.17.3"
itertools = "0.10.5"
logos = "0.13.0"
once_cell = "1.17.1"
rustyline = "11.0.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
shlex = "1.1.0"
sqlformat = "0.2.1"
strum = "0.24"
strum_macros = "0.24"
terminal_size = "0.2.6"
tokio = { version = "1.28.1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "parking_lot",
] }
toml = "0.7.3"
unicode-segmentation = "1.10.1"
url = { version = "2.3.1", default-features = false }

[build-dependencies]
vergen = { version = "8.1.3", features = ["build", "git", "gitcl"] }

[[bin]]
name = "bendsql"
path = "src/main.rs"
doctest = false
test = false
