[package]
name = "databend-client"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Databend Driver for Rust"
categories = ["database"]
keywords = ["databend", "database", "rust"]
repository = "https://github.com/databendcloud/databend-client"

[dependencies]
anyhow = "1.0.70"
http = "0.2.9"
reqwest = { version = "0.11.14", default-features = false, features = ["json"] }
serde = { version = "1.0.156", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.94", default-features = false, features = ["std"] }
tower = { version = "0.4.13", default-features = false }
tower-http = { version = "0.4.0", default-features = false }
url = { version = "2.3.1", default-features = false }
