[package]
name = "databend-python"
publish = false

version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]
name = "databend_driver"
doc = false

[dependencies]
databend-driver = { workspace = true, features = ["rustls", "flight-sql"] }
pyo3 = { version = "0.20", features = ["abi3-py37"] }
pyo3-asyncio = { version = "0.20", features = ["tokio-runtime"] }
tokio = "1.34"
tokio-stream = "0.1"
