[package]
name = "databend-python"
publish = false

version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
databend-client = { workspace = true }
databend-driver = { workspace = true, features = ["rustls", "flight-sql"] }

chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
futures = "0.3.28"
pyo3 = { version = "0.18.3", features = ["abi3-py37"] }
pyo3-asyncio = { version = "0.18", features = ["tokio-runtime"] }
tokio = "1.28.2"
