[package]
name = "databend-driver"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Databend Driver for Rust"
categories = ["database"]
keywords = ["databend", "database", "rust"]
repository = "https://github.com/databendcloud/databend-client"

[dependencies]
anyhow = "1.0.70"
databend-client = { path = "../core" }
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros"] }
