name: bindings nodejs

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
    paths:
      - 'bindings/nodejs/**'
      - ".github/workflows/bindings.nodejs.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/nodejs
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          cache-key: bindings-nodejs
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: "bindings/nodejs/yarn.lock"
      - name: Corepack
        run: corepack enable
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Check format
        run: yarn run prettier --check .
      - name: Build
        run: yarn build:debug
      - name: Check diff
        run: git diff --exit-code
      - name: Test
        run: yarn test

  build:
    name: build-${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: bindings/nodejs
    strategy:
      matrix:
        include:
          - { os: ubuntu, arch: x64, target: x86_64-unknown-linux-gnu }
          - { os: windows, arch: x64, target: x86_64-pc-windows-msvc }
          - { os: macos, arch: x64, target: x86_64-apple-darwin }
          - { os: macos, arch: arm64, target: aarch64-apple-darwin }
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: ./.github/actions/setup
        with:
          cache-key: bindings-nodejs
          target: ${{ matrix.target }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: "bindings/nodejs/yarn.lock"
      - name: Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: build
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == 'aarch64-apple-darwin' ]]; then
            sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
            export CC=$(xcrun -f clang)
            export CXX=$(xcrun -f clang++)
            SYSROOT=$(xcrun --sdk macosx --show-sdk-path)
            export CFLAGS="-isysroot $SYSROOT -isystem $SYSROOT"
          fi
          export NAPI_TARGET=${{ matrix.target }}
          yarn build
      - name: strip for macos
        if: matrix.os == 'macos'
        run: |
          strip -x *.node
      - uses: actions/upload-artifact@v3
        with:
          name: bindings-nodejs
          path: bindings/nodejs/*.node

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/nodejs
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
          cache-dependency-path: "bindings/nodejs/yarn.lock"
      - name: Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: bindings/nodejs/artifacts
      - name: Move artifacts
        run: yarn run napi artifacts
      - name: List packages
        run: ls -R ./npm
      - name: Add LICENSE
        working-directory: .
        run: cp LICENSE ./bindings/nodejs
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access public --provenance
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
