name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-11
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features -- --show-output

  test:
    runs-on: ubuntu-latest
    services:
      databend:
        image: datafuselabs/databend
        env:
          QUERY_DEFAULT_USER: databend
          QUERY_DEFAULT_PASSWORD: databend
          MINIO_ENABLED: true
        ports:
          - 8000:8000
          - 9000:9000
    steps:
      - uses: actions/checkout@v3
      - name: Verify Service Running
        run: |
          cid=$(docker ps -a | grep databend | cut -d' ' -f1)
          docker logs ${cid}
          curl -v http://localhost:8000/v1/health
      - name: Test
        uses: actions-rs/cargo@v1
        env:
          TEST_DATABEND_DSN: "databend://databend:databend@localhost:8000/default?sslmode=disable"
        with:
          command: test
          args: --all-features -- --show-output
