name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          cache-key: check
      - uses: ./.github/actions/check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}-latest
    name: build-${{ matrix.os }}-${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - { os: ubuntu, arch: x86_64, target: x86_64-unknown-linux-gnu }
          - { os: macos, arch: x86_64, target: x86_64-apple-darwin }
          - { os: windows, arch: x86_64, target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          cache-key: build
          target: ${{ matrix.target }}
      - run: cargo build

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          cache-key: unit
      - run: cargo test --all-features --lib -- --show-output

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          cache-key: integration
      - run: make -C tests test-core
      - run: make -C tests test-driver
      - run: make -C tests test-bendsql
      - run: make -C tests test-binding-python
      - run: sudo chown -R runner ~/.cargo/registry
