name: PR Assistant

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
