name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  crates:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - run: cargo install cargo-release
    - run: cargo release publish
