# .github/workflows/docker-publish.yml

name: TTC docker publish

on:
  push:
    branches:
      - main
    paths:
      - 'core/**'
      - 'driver/**'
      - 'ttc/**'
      - 'sql/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag
        run: echo "DOCKER_TAG=${{ startsWith(github.ref, 'refs/tags/') && github.ref[10:] || 'latest' }}" >> $GITHUB_ENV

      - name: Print Docker tag
        run: echo "Start to build and publish: datafuselabs/ttc-rust:$DOCKER_TAG"

      - name: TTC Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./ttc/Dockerfile
          tags: datafuselabs/ttc-rust:$DOCKER_TAG
