# .github/workflows/docker-publish.yml

name: Docker

on:
  push:
    branches:
      - main
    paths:
      - 'core/**'
      - 'driver/**'
      - 'ttc/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SUNDY_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SUNDY_DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./ttc/Dockerfile
          tags: sundyli/ttc-rust:latest
